site_name: pyControl
site_url: https://pycontrol.readthedocs.io/
site_description: Open source, Python based, behavioural experiment control.
site_author: Champalimaud Foundation

theme:
    name: readthedocs
    #custom_dir: cinder

repo_url: https://bitbucket.org/fchampalimaud/pycontrol-docs

nav:
- Home: index.md
- User Guide:
    - Graphical user interface (GUI): user-guide/graphical-user-interface.md
    - Command line interface (CLI): user-guide/command-line-interface.md
    - Programming tasks: user-guide/programming-tasks.md
    - Hardware: user-guide/hardware.md
    - Synchronisation: user-guide/synchronisation.md 
    - Importing data: user-guide/importing-data.md
#    - Source code installation: user-guide/source-code-installation.md
- Contributing: contributing.md

- About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

#extra_css:
#    - css/extra.css

#markdown_extensions:
#    - toc:
#        permalink: 
#    - admonition:

copyright: Copyright &copy; 2016 <a href="/release-notes/">Champalimaud Foundation</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Scientific Software Platform</a>.
#google_analytics: ['UA-27795084-5', 'mkdocs.org']
